.TH TEMPREAD
.SH NAME
tempread \- outputs temperature from sensor
.SH SYNOPSIS
.B
[\fB\-v\fR]
[\fB\-\-d\fR \fIDEVICE_SERIAL\fR]
.IR file ...
.SH DESCRIPTION
.B tempmonitor
Print temperature when no arguments.
-v prints 1wire temperature file.
-d lets user inputs device serial number.
.SH OPTIONS
.TP
.BR \-v ", " \-\-bits =\fIBITS\fR
